language: node_js
node_js:
  - "8"
os:
  -linux
services:
  - mongodb
  - elasticsearch
env:
  - MONGOSEARCH_TEST_HOST=mongodb://127.0.0.1:27017/test#test1 MONGOSTORE_TEST_HOST=mongodb://127.0.0.1:27017/test#test2 ELASTICSEARCH_TEST_HOST=127.0.0.1:9200#test
before_script:
  - sleep 15
script:
  - npm run docs
  - npm run test
deploy:
  provider: pages
  local_dir: node_docs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
