window.esdocSearchIndex = [
  [
    "node-collections-boilerplate/node-collections-boilerplate-nahid/cachedcollection.js~cachedcollection",
    "class/node-collections-boilerplate-nahid/CachedCollection.js~CachedCollection.html",
    "<span>CachedCollection</span> <span class=\"search-result-import-path\">node-collections-boilerplate/node-collections-boilerplate-nahid/CachedCollection.js</span>",
    "class"
  ],
  [
    "node-collections-boilerplate/node-collections-boilerplate-nahid/cachedcollection.js~collection",
    "variable/index.html#static-variable-Collection",
    "<span>Collection</span> <span class=\"search-result-import-path\">node-collections-boilerplate/node-collections-boilerplate-nahid/CachedCollection.js</span>",
    "variable"
  ],
  [
    "node-collections-boilerplate/node-collections-boilerplate-nahid/collection.js~collection",
    "class/node-collections-boilerplate-nahid/Collection.js~Collection.html",
    "<span>Collection</span> <span class=\"search-result-import-path\">node-collections-boilerplate/node-collections-boilerplate-nahid/Collection.js</span>",
    "class"
  ],
  [
    "node-collections-boilerplate/node-collections-boilerplate-nahid/storage/dynamostorage.js~dynamostorage",
    "class/node-collections-boilerplate-nahid/storage/DynamoStorage.js~DynamoStorage.html",
    "<span>DynamoStorage</span> <span class=\"search-result-import-path\">node-collections-boilerplate/node-collections-boilerplate-nahid/storage/DynamoStorage.js</span>",
    "class"
  ],
  [
    "node-collections-boilerplate/node-collections-boilerplate-nahid/storage/dynamostoragestreamnotifier.js~dynamostoragestreamnotifier",
    "class/node-collections-boilerplate-nahid/storage/DynamoStorageStreamNotifier.js~DynamoStorageStreamNotifier.html",
    "<span>DynamoStorageStreamNotifier</span> <span class=\"search-result-import-path\">node-collections-boilerplate/node-collections-boilerplate-nahid/storage/DynamoStorageStreamNotifier.js</span>",
    "class"
  ],
  [
    "node-collections-boilerplate/node-collections-boilerplate-nahid/search/elasticsearch.js~elasticsearch",
    "class/node-collections-boilerplate-nahid/search/ElasticSearch.js~ElasticSearch.html",
    "<span>ElasticSearch</span> <span class=\"search-result-import-path\">node-collections-boilerplate/node-collections-boilerplate-nahid/search/ElasticSearch.js</span>",
    "class"
  ],
  [
    "node-collections-boilerplate/node-collections-boilerplate-nahid/storage/storage.js~eventemitter",
    "variable/index.html#static-variable-EventEmitter",
    "<span>EventEmitter</span> <span class=\"search-result-import-path\">node-collections-boilerplate/node-collections-boilerplate-nahid/storage/Storage.js</span>",
    "variable"
  ],
  [
    "node-collections-boilerplate/node-collections-boilerplate-nahid/storage/fsstorage.js~fsstorage",
    "class/node-collections-boilerplate-nahid/storage/FSStorage.js~FSStorage.html",
    "<span>FSStorage</span> <span class=\"search-result-import-path\">node-collections-boilerplate/node-collections-boilerplate-nahid/storage/FSStorage.js</span>",
    "class"
  ],
  [
    "node-collections-boilerplate/node-collections-boilerplate-nahid/storage/memorystorage.js~memorystorage",
    "class/node-collections-boilerplate-nahid/storage/MemoryStorage.js~MemoryStorage.html",
    "<span>MemoryStorage</span> <span class=\"search-result-import-path\">node-collections-boilerplate/node-collections-boilerplate-nahid/storage/MemoryStorage.js</span>",
    "class"
  ],
  [
    "node-collections-boilerplate/node-collections-boilerplate-nahid/search/mongosearch.js~mongosearch",
    "class/node-collections-boilerplate-nahid/search/MongoSearch.js~MongoSearch.html",
    "<span>MongoSearch</span> <span class=\"search-result-import-path\">node-collections-boilerplate/node-collections-boilerplate-nahid/search/MongoSearch.js</span>",
    "class"
  ],
  [
    "node-collections-boilerplate/node-collections-boilerplate-nahid/storage/mongostorage.js~mongostorage",
    "class/node-collections-boilerplate-nahid/storage/MongoStorage.js~MongoStorage.html",
    "<span>MongoStorage</span> <span class=\"search-result-import-path\">node-collections-boilerplate/node-collections-boilerplate-nahid/storage/MongoStorage.js</span>",
    "class"
  ],
  [
    "node-collections-boilerplate/node-collections-boilerplate-nahid/search/nosearch.js~nosearch",
    "class/node-collections-boilerplate-nahid/search/NoSearch.js~NoSearch.html",
    "<span>NoSearch</span> <span class=\"search-result-import-path\">node-collections-boilerplate/node-collections-boilerplate-nahid/search/NoSearch.js</span>",
    "class"
  ],
  [
    "node-collections-boilerplate/node-collections-boilerplate-nahid/storage/s3storage.js~s3storage",
    "class/node-collections-boilerplate-nahid/storage/S3Storage.js~S3Storage.html",
    "<span>S3Storage</span> <span class=\"search-result-import-path\">node-collections-boilerplate/node-collections-boilerplate-nahid/storage/S3Storage.js</span>",
    "class"
  ],
  [
    "node-collections-boilerplate/node-collections-boilerplate-nahid/search/elasticsearch.js~search",
    "variable/index.html#static-variable-Search",
    "<span>Search</span> <span class=\"search-result-import-path\">node-collections-boilerplate/node-collections-boilerplate-nahid/search/ElasticSearch.js</span>",
    "variable"
  ],
  [
    "node-collections-boilerplate/node-collections-boilerplate-nahid/search/search.js~search",
    "class/node-collections-boilerplate-nahid/search/Search.js~Search.html",
    "<span>Search</span> <span class=\"search-result-import-path\">node-collections-boilerplate/node-collections-boilerplate-nahid/search/Search.js</span>",
    "class"
  ],
  [
    "node-collections-boilerplate/node-collections-boilerplate-nahid/storage/dynamostorage.js~storage",
    "variable/index.html#static-variable-Storage",
    "<span>Storage</span> <span class=\"search-result-import-path\">node-collections-boilerplate/node-collections-boilerplate-nahid/storage/DynamoStorage.js</span>",
    "variable"
  ],
  [
    "node-collections-boilerplate/node-collections-boilerplate-nahid/storage/storage.js~storage",
    "class/node-collections-boilerplate-nahid/storage/Storage.js~Storage.html",
    "<span>Storage</span> <span class=\"search-result-import-path\">node-collections-boilerplate/node-collections-boilerplate-nahid/storage/Storage.js</span>",
    "class"
  ],
  [
    "node-collections-boilerplate/node-collections-boilerplate-nahid/storage/dynamodecoderecord.js~dynamodecoderecord",
    "function/index.html#static-function-dynamoDecodeRecord",
    "<span>dynamoDecodeRecord</span> <span class=\"search-result-import-path\">node-collections-boilerplate/node-collections-boilerplate-nahid/storage/dynamoDecodeRecord.js</span>",
    "function"
  ],
  [
    "node-collections-boilerplate/node-collections-boilerplate-nahid/storage/dynamoencoderecord.js~dynamoencoderecord",
    "function/index.html#static-function-dynamoEncodeRecord",
    "<span>dynamoEncodeRecord</span> <span class=\"search-result-import-path\">node-collections-boilerplate/node-collections-boilerplate-nahid/storage/dynamoEncodeRecord.js</span>",
    "function"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~String",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~function",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~null",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~number",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~object",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~string",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "node-collections-boilerplate-nahid/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "node-collections-boilerplate-nahid/cachedcollection.js",
    "file/node-collections-boilerplate-nahid/CachedCollection.js.html",
    "node-collections-boilerplate-nahid/CachedCollection.js",
    "file"
  ],
  [
    "node-collections-boilerplate-nahid/cachedcollection.js~cachedcollection#createrecord",
    "class/node-collections-boilerplate-nahid/CachedCollection.js~CachedCollection.html#instance-method-createRecord",
    "node-collections-boilerplate-nahid/CachedCollection.js~CachedCollection#createRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/cachedcollection.js~cachedcollection#deleterecord",
    "class/node-collections-boilerplate-nahid/CachedCollection.js~CachedCollection.html#instance-method-deleteRecord",
    "node-collections-boilerplate-nahid/CachedCollection.js~CachedCollection#deleteRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/cachedcollection.js~cachedcollection#initialise",
    "class/node-collections-boilerplate-nahid/CachedCollection.js~CachedCollection.html#instance-method-initialise",
    "node-collections-boilerplate-nahid/CachedCollection.js~CachedCollection#initialise",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/cachedcollection.js~cachedcollection#lookup",
    "class/node-collections-boilerplate-nahid/CachedCollection.js~CachedCollection.html#instance-member-lookup",
    "node-collections-boilerplate-nahid/CachedCollection.js~CachedCollection#lookup",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/cachedcollection.js~cachedcollection#readrecord",
    "class/node-collections-boilerplate-nahid/CachedCollection.js~CachedCollection.html#instance-method-readRecord",
    "node-collections-boilerplate-nahid/CachedCollection.js~CachedCollection#readRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/cachedcollection.js~cachedcollection#searchrecords",
    "class/node-collections-boilerplate-nahid/CachedCollection.js~CachedCollection.html#instance-method-searchRecords",
    "node-collections-boilerplate-nahid/CachedCollection.js~CachedCollection#searchRecords",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/cachedcollection.js~cachedcollection#updaterecord",
    "class/node-collections-boilerplate-nahid/CachedCollection.js~CachedCollection.html#instance-method-updateRecord",
    "node-collections-boilerplate-nahid/CachedCollection.js~CachedCollection#updateRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/collection.js",
    "file/node-collections-boilerplate-nahid/Collection.js.html",
    "node-collections-boilerplate-nahid/Collection.js",
    "file"
  ],
  [
    "node-collections-boilerplate-nahid/collection.js~collection#collectionname",
    "class/node-collections-boilerplate-nahid/Collection.js~Collection.html#instance-member-collectionName",
    "node-collections-boilerplate-nahid/Collection.js~Collection#collectionName",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/collection.js~collection#constructor",
    "class/node-collections-boilerplate-nahid/Collection.js~Collection.html#instance-constructor-constructor",
    "node-collections-boilerplate-nahid/Collection.js~Collection#constructor",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/collection.js~collection#createrecord",
    "class/node-collections-boilerplate-nahid/Collection.js~Collection.html#instance-method-createRecord",
    "node-collections-boilerplate-nahid/Collection.js~Collection#createRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/collection.js~collection#deleterecord",
    "class/node-collections-boilerplate-nahid/Collection.js~Collection.html#instance-method-deleteRecord",
    "node-collections-boilerplate-nahid/Collection.js~Collection#deleteRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/collection.js~collection#initialise",
    "class/node-collections-boilerplate-nahid/Collection.js~Collection.html#instance-method-initialise",
    "node-collections-boilerplate-nahid/Collection.js~Collection#initialise",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/collection.js~collection#primarykey",
    "class/node-collections-boilerplate-nahid/Collection.js~Collection.html#instance-member-primaryKey",
    "node-collections-boilerplate-nahid/Collection.js~Collection#primaryKey",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/collection.js~collection#readrecord",
    "class/node-collections-boilerplate-nahid/Collection.js~Collection.html#instance-method-readRecord",
    "node-collections-boilerplate-nahid/Collection.js~Collection#readRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/collection.js~collection#search",
    "class/node-collections-boilerplate-nahid/Collection.js~Collection.html#instance-member-search",
    "node-collections-boilerplate-nahid/Collection.js~Collection#search",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/collection.js~collection#searchmeta",
    "class/node-collections-boilerplate-nahid/Collection.js~Collection.html#instance-member-searchMeta",
    "node-collections-boilerplate-nahid/Collection.js~Collection#searchMeta",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/collection.js~collection#searchrecords",
    "class/node-collections-boilerplate-nahid/Collection.js~Collection.html#instance-method-searchRecords",
    "node-collections-boilerplate-nahid/Collection.js~Collection#searchRecords",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/collection.js~collection#storage",
    "class/node-collections-boilerplate-nahid/Collection.js~Collection.html#instance-member-storage",
    "node-collections-boilerplate-nahid/Collection.js~Collection#storage",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/collection.js~collection#striprecord",
    "class/node-collections-boilerplate-nahid/Collection.js~Collection.html#instance-method-stripRecord",
    "node-collections-boilerplate-nahid/Collection.js~Collection#stripRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/collection.js~collection#updatefield",
    "class/node-collections-boilerplate-nahid/Collection.js~Collection.html#instance-method-updateField",
    "node-collections-boilerplate-nahid/Collection.js~Collection#updateField",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/collection.js~collection#updaterecord",
    "class/node-collections-boilerplate-nahid/Collection.js~Collection.html#instance-method-updateRecord",
    "node-collections-boilerplate-nahid/Collection.js~Collection#updateRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/collection.js~collection.create",
    "class/node-collections-boilerplate-nahid/Collection.js~Collection.html#static-method-create",
    "node-collections-boilerplate-nahid/Collection.js~Collection.create",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/search/elasticsearch.js",
    "file/node-collections-boilerplate-nahid/search/ElasticSearch.js.html",
    "node-collections-boilerplate-nahid/search/ElasticSearch.js",
    "file"
  ],
  [
    "node-collections-boilerplate-nahid/search/elasticsearch.js~elasticsearch#client",
    "class/node-collections-boilerplate-nahid/search/ElasticSearch.js~ElasticSearch.html#instance-member-client",
    "node-collections-boilerplate-nahid/search/ElasticSearch.js~ElasticSearch#client",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/search/elasticsearch.js~elasticsearch#connect",
    "class/node-collections-boilerplate-nahid/search/ElasticSearch.js~ElasticSearch.html#instance-method-connect",
    "node-collections-boilerplate-nahid/search/ElasticSearch.js~ElasticSearch#connect",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/search/elasticsearch.js~elasticsearch#createrecord",
    "class/node-collections-boilerplate-nahid/search/ElasticSearch.js~ElasticSearch.html#instance-method-createRecord",
    "node-collections-boilerplate-nahid/search/ElasticSearch.js~ElasticSearch#createRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/search/elasticsearch.js~elasticsearch#deleterecord",
    "class/node-collections-boilerplate-nahid/search/ElasticSearch.js~ElasticSearch.html#instance-method-deleteRecord",
    "node-collections-boilerplate-nahid/search/ElasticSearch.js~ElasticSearch#deleteRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/search/elasticsearch.js~elasticsearch#initialise",
    "class/node-collections-boilerplate-nahid/search/ElasticSearch.js~ElasticSearch.html#instance-method-initialise",
    "node-collections-boilerplate-nahid/search/ElasticSearch.js~ElasticSearch#initialise",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/search/elasticsearch.js~elasticsearch#searchmeta",
    "class/node-collections-boilerplate-nahid/search/ElasticSearch.js~ElasticSearch.html#instance-member-searchMeta",
    "node-collections-boilerplate-nahid/search/ElasticSearch.js~ElasticSearch#searchMeta",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/search/elasticsearch.js~elasticsearch#searchrecords",
    "class/node-collections-boilerplate-nahid/search/ElasticSearch.js~ElasticSearch.html#instance-method-searchRecords",
    "node-collections-boilerplate-nahid/search/ElasticSearch.js~ElasticSearch#searchRecords",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/search/elasticsearch.js~elasticsearch#updaterecord",
    "class/node-collections-boilerplate-nahid/search/ElasticSearch.js~ElasticSearch.html#instance-method-updateRecord",
    "node-collections-boilerplate-nahid/search/ElasticSearch.js~ElasticSearch#updateRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/search/mongosearch.js",
    "file/node-collections-boilerplate-nahid/search/MongoSearch.js.html",
    "node-collections-boilerplate-nahid/search/MongoSearch.js",
    "file"
  ],
  [
    "node-collections-boilerplate-nahid/search/mongosearch.js~mongosearch#initialise",
    "class/node-collections-boilerplate-nahid/search/MongoSearch.js~MongoSearch.html#instance-method-initialise",
    "node-collections-boilerplate-nahid/search/MongoSearch.js~MongoSearch#initialise",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/search/mongosearch.js~mongosearch#searchrecords",
    "class/node-collections-boilerplate-nahid/search/MongoSearch.js~MongoSearch.html#instance-method-searchRecords",
    "node-collections-boilerplate-nahid/search/MongoSearch.js~MongoSearch#searchRecords",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/search/nosearch.js",
    "file/node-collections-boilerplate-nahid/search/NoSearch.js.html",
    "node-collections-boilerplate-nahid/search/NoSearch.js",
    "file"
  ],
  [
    "node-collections-boilerplate-nahid/search/nosearch.js~nosearch#createrecord",
    "class/node-collections-boilerplate-nahid/search/NoSearch.js~NoSearch.html#instance-method-createRecord",
    "node-collections-boilerplate-nahid/search/NoSearch.js~NoSearch#createRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/search/nosearch.js~nosearch#deleterecord",
    "class/node-collections-boilerplate-nahid/search/NoSearch.js~NoSearch.html#instance-method-deleteRecord",
    "node-collections-boilerplate-nahid/search/NoSearch.js~NoSearch#deleteRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/search/nosearch.js~nosearch#ids",
    "class/node-collections-boilerplate-nahid/search/NoSearch.js~NoSearch.html#instance-member-ids",
    "node-collections-boilerplate-nahid/search/NoSearch.js~NoSearch#ids",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/search/nosearch.js~nosearch#initialise",
    "class/node-collections-boilerplate-nahid/search/NoSearch.js~NoSearch.html#instance-method-initialise",
    "node-collections-boilerplate-nahid/search/NoSearch.js~NoSearch#initialise",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/search/nosearch.js~nosearch#searchrecords",
    "class/node-collections-boilerplate-nahid/search/NoSearch.js~NoSearch.html#instance-method-searchRecords",
    "node-collections-boilerplate-nahid/search/NoSearch.js~NoSearch#searchRecords",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/search/nosearch.js~nosearch#updaterecord",
    "class/node-collections-boilerplate-nahid/search/NoSearch.js~NoSearch.html#instance-method-updateRecord",
    "node-collections-boilerplate-nahid/search/NoSearch.js~NoSearch#updateRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/search/search.js",
    "file/node-collections-boilerplate-nahid/search/Search.js.html",
    "node-collections-boilerplate-nahid/search/Search.js",
    "file"
  ],
  [
    "node-collections-boilerplate-nahid/search/search.js~search#collectionname",
    "class/node-collections-boilerplate-nahid/search/Search.js~Search.html#instance-member-collectionName",
    "node-collections-boilerplate-nahid/search/Search.js~Search#collectionName",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/search/search.js~search#connect",
    "class/node-collections-boilerplate-nahid/search/Search.js~Search.html#instance-method-connect",
    "node-collections-boilerplate-nahid/search/Search.js~Search#connect",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/search/search.js~search#connectionstring",
    "class/node-collections-boilerplate-nahid/search/Search.js~Search.html#instance-member-connectionString",
    "node-collections-boilerplate-nahid/search/Search.js~Search#connectionString",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/search/search.js~search#constructor",
    "class/node-collections-boilerplate-nahid/search/Search.js~Search.html#instance-constructor-constructor",
    "node-collections-boilerplate-nahid/search/Search.js~Search#constructor",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/search/search.js~search#createrecord",
    "class/node-collections-boilerplate-nahid/search/Search.js~Search.html#instance-method-createRecord",
    "node-collections-boilerplate-nahid/search/Search.js~Search#createRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/search/search.js~search#deleterecord",
    "class/node-collections-boilerplate-nahid/search/Search.js~Search.html#instance-method-deleteRecord",
    "node-collections-boilerplate-nahid/search/Search.js~Search#deleteRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/search/search.js~search#initialise",
    "class/node-collections-boilerplate-nahid/search/Search.js~Search.html#instance-method-initialise",
    "node-collections-boilerplate-nahid/search/Search.js~Search#initialise",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/search/search.js~search#primarykey",
    "class/node-collections-boilerplate-nahid/search/Search.js~Search.html#instance-member-primaryKey",
    "node-collections-boilerplate-nahid/search/Search.js~Search#primaryKey",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/search/search.js~search#searchrecords",
    "class/node-collections-boilerplate-nahid/search/Search.js~Search.html#instance-method-searchRecords",
    "node-collections-boilerplate-nahid/search/Search.js~Search#searchRecords",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/search/search.js~search#updaterecord",
    "class/node-collections-boilerplate-nahid/search/Search.js~Search.html#instance-method-updateRecord",
    "node-collections-boilerplate-nahid/search/Search.js~Search#updateRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/dynamostorage.js",
    "file/node-collections-boilerplate-nahid/storage/DynamoStorage.js.html",
    "node-collections-boilerplate-nahid/storage/DynamoStorage.js",
    "file"
  ],
  [
    "node-collections-boilerplate-nahid/storage/dynamostorage.js~dynamostorage#connect",
    "class/node-collections-boilerplate-nahid/storage/DynamoStorage.js~DynamoStorage.html#instance-method-connect",
    "node-collections-boilerplate-nahid/storage/DynamoStorage.js~DynamoStorage#connect",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/dynamostorage.js~dynamostorage#constructor",
    "class/node-collections-boilerplate-nahid/storage/DynamoStorage.js~DynamoStorage.html#instance-constructor-constructor",
    "node-collections-boilerplate-nahid/storage/DynamoStorage.js~DynamoStorage#constructor",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/dynamostorage.js~dynamostorage#createrecord",
    "class/node-collections-boilerplate-nahid/storage/DynamoStorage.js~DynamoStorage.html#instance-method-createRecord",
    "node-collections-boilerplate-nahid/storage/DynamoStorage.js~DynamoStorage#createRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/dynamostorage.js~dynamostorage#db",
    "class/node-collections-boilerplate-nahid/storage/DynamoStorage.js~DynamoStorage.html#instance-member-db",
    "node-collections-boilerplate-nahid/storage/DynamoStorage.js~DynamoStorage#db",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/storage/dynamostorage.js~dynamostorage#deleterecord",
    "class/node-collections-boilerplate-nahid/storage/DynamoStorage.js~DynamoStorage.html#instance-method-deleteRecord",
    "node-collections-boilerplate-nahid/storage/DynamoStorage.js~DynamoStorage#deleteRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/dynamostorage.js~dynamostorage#readallrecords",
    "class/node-collections-boilerplate-nahid/storage/DynamoStorage.js~DynamoStorage.html#instance-method-readAllRecords",
    "node-collections-boilerplate-nahid/storage/DynamoStorage.js~DynamoStorage#readAllRecords",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/dynamostorage.js~dynamostorage#readrecord",
    "class/node-collections-boilerplate-nahid/storage/DynamoStorage.js~DynamoStorage.html#instance-method-readRecord",
    "node-collections-boilerplate-nahid/storage/DynamoStorage.js~DynamoStorage#readRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/dynamostorage.js~dynamostorage#region",
    "class/node-collections-boilerplate-nahid/storage/DynamoStorage.js~DynamoStorage.html#instance-member-region",
    "node-collections-boilerplate-nahid/storage/DynamoStorage.js~DynamoStorage#region",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/storage/dynamostorage.js~dynamostorage#updaterecord",
    "class/node-collections-boilerplate-nahid/storage/DynamoStorage.js~DynamoStorage.html#instance-method-updateRecord",
    "node-collections-boilerplate-nahid/storage/DynamoStorage.js~DynamoStorage#updateRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/dynamostorage.js~dynamostorage#usestreams",
    "class/node-collections-boilerplate-nahid/storage/DynamoStorage.js~DynamoStorage.html#instance-member-useStreams",
    "node-collections-boilerplate-nahid/storage/DynamoStorage.js~DynamoStorage#useStreams",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/storage/dynamostoragestreamnotifier.js",
    "file/node-collections-boilerplate-nahid/storage/DynamoStorageStreamNotifier.js.html",
    "node-collections-boilerplate-nahid/storage/DynamoStorageStreamNotifier.js",
    "file"
  ],
  [
    "node-collections-boilerplate-nahid/storage/dynamostoragestreamnotifier.js~dynamostoragestreamnotifier#connect",
    "class/node-collections-boilerplate-nahid/storage/DynamoStorageStreamNotifier.js~DynamoStorageStreamNotifier.html#instance-method-connect",
    "node-collections-boilerplate-nahid/storage/DynamoStorageStreamNotifier.js~DynamoStorageStreamNotifier#connect",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/dynamostoragestreamnotifier.js~dynamostoragestreamnotifier#constructor",
    "class/node-collections-boilerplate-nahid/storage/DynamoStorageStreamNotifier.js~DynamoStorageStreamNotifier.html#instance-constructor-constructor",
    "node-collections-boilerplate-nahid/storage/DynamoStorageStreamNotifier.js~DynamoStorageStreamNotifier#constructor",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/dynamostoragestreamnotifier.js~dynamostoragestreamnotifier#shardid",
    "class/node-collections-boilerplate-nahid/storage/DynamoStorageStreamNotifier.js~DynamoStorageStreamNotifier.html#instance-member-shardId",
    "node-collections-boilerplate-nahid/storage/DynamoStorageStreamNotifier.js~DynamoStorageStreamNotifier#shardId",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/storage/dynamostoragestreamnotifier.js~dynamostoragestreamnotifier#sharditerator",
    "class/node-collections-boilerplate-nahid/storage/DynamoStorageStreamNotifier.js~DynamoStorageStreamNotifier.html#instance-member-shardIterator",
    "node-collections-boilerplate-nahid/storage/DynamoStorageStreamNotifier.js~DynamoStorageStreamNotifier#shardIterator",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/storage/dynamostoragestreamnotifier.js~dynamostoragestreamnotifier#storage",
    "class/node-collections-boilerplate-nahid/storage/DynamoStorageStreamNotifier.js~DynamoStorageStreamNotifier.html#instance-member-storage",
    "node-collections-boilerplate-nahid/storage/DynamoStorageStreamNotifier.js~DynamoStorageStreamNotifier#storage",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/storage/dynamostoragestreamnotifier.js~dynamostoragestreamnotifier#stream",
    "class/node-collections-boilerplate-nahid/storage/DynamoStorageStreamNotifier.js~DynamoStorageStreamNotifier.html#instance-member-stream",
    "node-collections-boilerplate-nahid/storage/DynamoStorageStreamNotifier.js~DynamoStorageStreamNotifier#stream",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/storage/dynamostoragestreamnotifier.js~dynamostoragestreamnotifier#streamarn",
    "class/node-collections-boilerplate-nahid/storage/DynamoStorageStreamNotifier.js~DynamoStorageStreamNotifier.html#instance-member-streamArn",
    "node-collections-boilerplate-nahid/storage/DynamoStorageStreamNotifier.js~DynamoStorageStreamNotifier#streamArn",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/storage/dynamostoragestreamnotifier.js~dynamostoragestreamnotifier#updatecheck",
    "class/node-collections-boilerplate-nahid/storage/DynamoStorageStreamNotifier.js~DynamoStorageStreamNotifier.html#instance-method-updateCheck",
    "node-collections-boilerplate-nahid/storage/DynamoStorageStreamNotifier.js~DynamoStorageStreamNotifier#updateCheck",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/fsstorage.js",
    "file/node-collections-boilerplate-nahid/storage/FSStorage.js.html",
    "node-collections-boilerplate-nahid/storage/FSStorage.js",
    "file"
  ],
  [
    "node-collections-boilerplate-nahid/storage/fsstorage.js~fsstorage#constructor",
    "class/node-collections-boilerplate-nahid/storage/FSStorage.js~FSStorage.html#instance-constructor-constructor",
    "node-collections-boilerplate-nahid/storage/FSStorage.js~FSStorage#constructor",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/fsstorage.js~fsstorage#createrecord",
    "class/node-collections-boilerplate-nahid/storage/FSStorage.js~FSStorage.html#instance-method-createRecord",
    "node-collections-boilerplate-nahid/storage/FSStorage.js~FSStorage#createRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/fsstorage.js~fsstorage#deleterecord",
    "class/node-collections-boilerplate-nahid/storage/FSStorage.js~FSStorage.html#instance-method-deleteRecord",
    "node-collections-boilerplate-nahid/storage/FSStorage.js~FSStorage#deleteRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/fsstorage.js~fsstorage#dirname",
    "class/node-collections-boilerplate-nahid/storage/FSStorage.js~FSStorage.html#instance-member-dirname",
    "node-collections-boilerplate-nahid/storage/FSStorage.js~FSStorage#dirname",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/storage/fsstorage.js~fsstorage#list",
    "class/node-collections-boilerplate-nahid/storage/FSStorage.js~FSStorage.html#instance-member-list",
    "node-collections-boilerplate-nahid/storage/FSStorage.js~FSStorage#list",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/storage/fsstorage.js~fsstorage#listitems",
    "class/node-collections-boilerplate-nahid/storage/FSStorage.js~FSStorage.html#instance-method-listItems",
    "node-collections-boilerplate-nahid/storage/FSStorage.js~FSStorage#listItems",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/fsstorage.js~fsstorage#readallrecords",
    "class/node-collections-boilerplate-nahid/storage/FSStorage.js~FSStorage.html#instance-method-readAllRecords",
    "node-collections-boilerplate-nahid/storage/FSStorage.js~FSStorage#readAllRecords",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/fsstorage.js~fsstorage#readrecord",
    "class/node-collections-boilerplate-nahid/storage/FSStorage.js~FSStorage.html#instance-method-readRecord",
    "node-collections-boilerplate-nahid/storage/FSStorage.js~FSStorage#readRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/fsstorage.js~fsstorage#updatecheckimpl",
    "class/node-collections-boilerplate-nahid/storage/FSStorage.js~FSStorage.html#instance-method-updateCheckImpl",
    "node-collections-boilerplate-nahid/storage/FSStorage.js~FSStorage#updateCheckImpl",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/fsstorage.js~fsstorage#updaterecord",
    "class/node-collections-boilerplate-nahid/storage/FSStorage.js~FSStorage.html#instance-method-updateRecord",
    "node-collections-boilerplate-nahid/storage/FSStorage.js~FSStorage#updateRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/memorystorage.js",
    "file/node-collections-boilerplate-nahid/storage/MemoryStorage.js.html",
    "node-collections-boilerplate-nahid/storage/MemoryStorage.js",
    "file"
  ],
  [
    "node-collections-boilerplate-nahid/storage/memorystorage.js~memorystorage#array",
    "class/node-collections-boilerplate-nahid/storage/MemoryStorage.js~MemoryStorage.html#instance-member-array",
    "node-collections-boilerplate-nahid/storage/MemoryStorage.js~MemoryStorage#array",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/storage/memorystorage.js~memorystorage#constructor",
    "class/node-collections-boilerplate-nahid/storage/MemoryStorage.js~MemoryStorage.html#instance-constructor-constructor",
    "node-collections-boilerplate-nahid/storage/MemoryStorage.js~MemoryStorage#constructor",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/memorystorage.js~memorystorage#createrecord",
    "class/node-collections-boilerplate-nahid/storage/MemoryStorage.js~MemoryStorage.html#instance-method-createRecord",
    "node-collections-boilerplate-nahid/storage/MemoryStorage.js~MemoryStorage#createRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/memorystorage.js~memorystorage#deleterecord",
    "class/node-collections-boilerplate-nahid/storage/MemoryStorage.js~MemoryStorage.html#instance-method-deleteRecord",
    "node-collections-boilerplate-nahid/storage/MemoryStorage.js~MemoryStorage#deleteRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/memorystorage.js~memorystorage#readallrecords",
    "class/node-collections-boilerplate-nahid/storage/MemoryStorage.js~MemoryStorage.html#instance-method-readAllRecords",
    "node-collections-boilerplate-nahid/storage/MemoryStorage.js~MemoryStorage#readAllRecords",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/memorystorage.js~memorystorage#readrecord",
    "class/node-collections-boilerplate-nahid/storage/MemoryStorage.js~MemoryStorage.html#instance-method-readRecord",
    "node-collections-boilerplate-nahid/storage/MemoryStorage.js~MemoryStorage#readRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/memorystorage.js~memorystorage#updaterecord",
    "class/node-collections-boilerplate-nahid/storage/MemoryStorage.js~MemoryStorage.html#instance-method-updateRecord",
    "node-collections-boilerplate-nahid/storage/MemoryStorage.js~MemoryStorage#updateRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/mongostorage.js",
    "file/node-collections-boilerplate-nahid/storage/MongoStorage.js.html",
    "node-collections-boilerplate-nahid/storage/MongoStorage.js",
    "file"
  ],
  [
    "node-collections-boilerplate-nahid/storage/mongostorage.js~mongostorage#collection",
    "class/node-collections-boilerplate-nahid/storage/MongoStorage.js~MongoStorage.html#instance-member-collection",
    "node-collections-boilerplate-nahid/storage/MongoStorage.js~MongoStorage#collection",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/storage/mongostorage.js~mongostorage#connect",
    "class/node-collections-boilerplate-nahid/storage/MongoStorage.js~MongoStorage.html#instance-method-connect",
    "node-collections-boilerplate-nahid/storage/MongoStorage.js~MongoStorage#connect",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/mongostorage.js~mongostorage#createrecord",
    "class/node-collections-boilerplate-nahid/storage/MongoStorage.js~MongoStorage.html#instance-method-createRecord",
    "node-collections-boilerplate-nahid/storage/MongoStorage.js~MongoStorage#createRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/mongostorage.js~mongostorage#database",
    "class/node-collections-boilerplate-nahid/storage/MongoStorage.js~MongoStorage.html#instance-member-database",
    "node-collections-boilerplate-nahid/storage/MongoStorage.js~MongoStorage#database",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/storage/mongostorage.js~mongostorage#deleterecord",
    "class/node-collections-boilerplate-nahid/storage/MongoStorage.js~MongoStorage.html#instance-method-deleteRecord",
    "node-collections-boilerplate-nahid/storage/MongoStorage.js~MongoStorage#deleteRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/mongostorage.js~mongostorage#readallrecords",
    "class/node-collections-boilerplate-nahid/storage/MongoStorage.js~MongoStorage.html#instance-method-readAllRecords",
    "node-collections-boilerplate-nahid/storage/MongoStorage.js~MongoStorage#readAllRecords",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/mongostorage.js~mongostorage#readrecord",
    "class/node-collections-boilerplate-nahid/storage/MongoStorage.js~MongoStorage.html#instance-method-readRecord",
    "node-collections-boilerplate-nahid/storage/MongoStorage.js~MongoStorage#readRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/mongostorage.js~mongostorage#updaterecord",
    "class/node-collections-boilerplate-nahid/storage/MongoStorage.js~MongoStorage.html#instance-method-updateRecord",
    "node-collections-boilerplate-nahid/storage/MongoStorage.js~MongoStorage#updateRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/s3storage.js",
    "file/node-collections-boilerplate-nahid/storage/S3Storage.js.html",
    "node-collections-boilerplate-nahid/storage/S3Storage.js",
    "file"
  ],
  [
    "node-collections-boilerplate-nahid/storage/s3storage.js~s3storage#connect",
    "class/node-collections-boilerplate-nahid/storage/S3Storage.js~S3Storage.html#instance-method-connect",
    "node-collections-boilerplate-nahid/storage/S3Storage.js~S3Storage#connect",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/s3storage.js~s3storage#constructor",
    "class/node-collections-boilerplate-nahid/storage/S3Storage.js~S3Storage.html#instance-constructor-constructor",
    "node-collections-boilerplate-nahid/storage/S3Storage.js~S3Storage#constructor",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/s3storage.js~s3storage#createrecord",
    "class/node-collections-boilerplate-nahid/storage/S3Storage.js~S3Storage.html#instance-method-createRecord",
    "node-collections-boilerplate-nahid/storage/S3Storage.js~S3Storage#createRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/s3storage.js~s3storage#deleterecord",
    "class/node-collections-boilerplate-nahid/storage/S3Storage.js~S3Storage.html#instance-method-deleteRecord",
    "node-collections-boilerplate-nahid/storage/S3Storage.js~S3Storage#deleteRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/s3storage.js~s3storage#listitems",
    "class/node-collections-boilerplate-nahid/storage/S3Storage.js~S3Storage.html#instance-method-listItems",
    "node-collections-boilerplate-nahid/storage/S3Storage.js~S3Storage#listItems",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/s3storage.js~s3storage#readallrecords",
    "class/node-collections-boilerplate-nahid/storage/S3Storage.js~S3Storage.html#instance-method-readAllRecords",
    "node-collections-boilerplate-nahid/storage/S3Storage.js~S3Storage#readAllRecords",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/s3storage.js~s3storage#readrecord",
    "class/node-collections-boilerplate-nahid/storage/S3Storage.js~S3Storage.html#instance-method-readRecord",
    "node-collections-boilerplate-nahid/storage/S3Storage.js~S3Storage#readRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/s3storage.js~s3storage#region",
    "class/node-collections-boilerplate-nahid/storage/S3Storage.js~S3Storage.html#instance-member-region",
    "node-collections-boilerplate-nahid/storage/S3Storage.js~S3Storage#region",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/storage/s3storage.js~s3storage#s3",
    "class/node-collections-boilerplate-nahid/storage/S3Storage.js~S3Storage.html#instance-member-s3",
    "node-collections-boilerplate-nahid/storage/S3Storage.js~S3Storage#s3",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/storage/s3storage.js~s3storage#updatecheckimpl",
    "class/node-collections-boilerplate-nahid/storage/S3Storage.js~S3Storage.html#instance-method-updateCheckImpl",
    "node-collections-boilerplate-nahid/storage/S3Storage.js~S3Storage#updateCheckImpl",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/s3storage.js~s3storage#updaterecord",
    "class/node-collections-boilerplate-nahid/storage/S3Storage.js~S3Storage.html#instance-method-updateRecord",
    "node-collections-boilerplate-nahid/storage/S3Storage.js~S3Storage#updateRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/storage.js",
    "file/node-collections-boilerplate-nahid/storage/Storage.js.html",
    "node-collections-boilerplate-nahid/storage/Storage.js",
    "file"
  ],
  [
    "node-collections-boilerplate-nahid/storage/storage.js~storage#bruteforcenotified",
    "class/node-collections-boilerplate-nahid/storage/Storage.js~Storage.html#instance-member-bruteForceNotified",
    "node-collections-boilerplate-nahid/storage/Storage.js~Storage#bruteForceNotified",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/storage/storage.js~storage#collectionname",
    "class/node-collections-boilerplate-nahid/storage/Storage.js~Storage.html#instance-member-collectionName",
    "node-collections-boilerplate-nahid/storage/Storage.js~Storage#collectionName",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/storage/storage.js~storage#connect",
    "class/node-collections-boilerplate-nahid/storage/Storage.js~Storage.html#instance-method-connect",
    "node-collections-boilerplate-nahid/storage/Storage.js~Storage#connect",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/storage.js~storage#connectionstring",
    "class/node-collections-boilerplate-nahid/storage/Storage.js~Storage.html#instance-member-connectionString",
    "node-collections-boilerplate-nahid/storage/Storage.js~Storage#connectionString",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/storage/storage.js~storage#constructor",
    "class/node-collections-boilerplate-nahid/storage/Storage.js~Storage.html#instance-constructor-constructor",
    "node-collections-boilerplate-nahid/storage/Storage.js~Storage#constructor",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/storage.js~storage#createrecord",
    "class/node-collections-boilerplate-nahid/storage/Storage.js~Storage.html#instance-method-createRecord",
    "node-collections-boilerplate-nahid/storage/Storage.js~Storage#createRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/storage.js~storage#deleterecord",
    "class/node-collections-boilerplate-nahid/storage/Storage.js~Storage.html#instance-method-deleteRecord",
    "node-collections-boilerplate-nahid/storage/Storage.js~Storage#deleteRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/storage.js~storage#lookup",
    "class/node-collections-boilerplate-nahid/storage/Storage.js~Storage.html#instance-member-lookup",
    "node-collections-boilerplate-nahid/storage/Storage.js~Storage#lookup",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/storage/storage.js~storage#primarykey",
    "class/node-collections-boilerplate-nahid/storage/Storage.js~Storage.html#instance-member-primaryKey",
    "node-collections-boilerplate-nahid/storage/Storage.js~Storage#primaryKey",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/storage/storage.js~storage#readallrecords",
    "class/node-collections-boilerplate-nahid/storage/Storage.js~Storage.html#instance-method-readAllRecords",
    "node-collections-boilerplate-nahid/storage/Storage.js~Storage#readAllRecords",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/storage.js~storage#readrecord",
    "class/node-collections-boilerplate-nahid/storage/Storage.js~Storage.html#instance-method-readRecord",
    "node-collections-boilerplate-nahid/storage/Storage.js~Storage#readRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/storage.js~storage#startrecordupdatecheck",
    "class/node-collections-boilerplate-nahid/storage/Storage.js~Storage.html#instance-method-startRecordUpdateCheck",
    "node-collections-boilerplate-nahid/storage/Storage.js~Storage#startRecordUpdateCheck",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/storage.js~storage#stoprecordupdatecheck",
    "class/node-collections-boilerplate-nahid/storage/Storage.js~Storage.html#instance-method-stopRecordUpdateCheck",
    "node-collections-boilerplate-nahid/storage/Storage.js~Storage#stopRecordUpdateCheck",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/storage.js~storage#timeout",
    "class/node-collections-boilerplate-nahid/storage/Storage.js~Storage.html#instance-member-timeout",
    "node-collections-boilerplate-nahid/storage/Storage.js~Storage#timeout",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/storage/storage.js~storage#updatecheckimpl",
    "class/node-collections-boilerplate-nahid/storage/Storage.js~Storage.html#instance-method-updateCheckImpl",
    "node-collections-boilerplate-nahid/storage/Storage.js~Storage#updateCheckImpl",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/storage.js~storage#updateinterval",
    "class/node-collections-boilerplate-nahid/storage/Storage.js~Storage.html#instance-member-updateInterval",
    "node-collections-boilerplate-nahid/storage/Storage.js~Storage#updateInterval",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/storage/storage.js~storage#updateintervalmax",
    "class/node-collections-boilerplate-nahid/storage/Storage.js~Storage.html#instance-member-updateIntervalMax",
    "node-collections-boilerplate-nahid/storage/Storage.js~Storage#updateIntervalMax",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/storage/storage.js~storage#updateintervalslowdownrate",
    "class/node-collections-boilerplate-nahid/storage/Storage.js~Storage.html#instance-member-updateIntervalSlowdownRate",
    "node-collections-boilerplate-nahid/storage/Storage.js~Storage#updateIntervalSlowdownRate",
    "member"
  ],
  [
    "node-collections-boilerplate-nahid/storage/storage.js~storage#updaterecord",
    "class/node-collections-boilerplate-nahid/storage/Storage.js~Storage.html#instance-method-updateRecord",
    "node-collections-boilerplate-nahid/storage/Storage.js~Storage#updateRecord",
    "method"
  ],
  [
    "node-collections-boilerplate-nahid/storage/dynamodecoderecord.js",
    "file/node-collections-boilerplate-nahid/storage/dynamoDecodeRecord.js.html",
    "node-collections-boilerplate-nahid/storage/dynamoDecodeRecord.js",
    "file"
  ],
  [
    "node-collections-boilerplate-nahid/storage/dynamoencoderecord.js",
    "file/node-collections-boilerplate-nahid/storage/dynamoEncodeRecord.js.html",
    "node-collections-boilerplate-nahid/storage/dynamoEncodeRecord.js",
    "file"
  ]
]